#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduFileStock.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="nurlans1_edufilestock")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcontact(contact instance);
    partial void Updatecontact(contact instance);
    partial void Deletecontact(contact instance);
    partial void Insertdetail(detail instance);
    partial void Updatedetail(detail instance);
    partial void Deletedetail(detail instance);
    partial void InsertIstifadeci(Istifadeci instance);
    partial void UpdateIstifadeci(Istifadeci instance);
    partial void DeleteIstifadeci(Istifadeci instance);
    partial void Insertistip(istip instance);
    partial void Updateistip(istip instance);
    partial void Deleteistip(istip instance);
    partial void Insertmelumataltli(melumataltli instance);
    partial void Updatemelumataltli(melumataltli instance);
    partial void Deletemelumataltli(melumataltli instance);
    partial void Insertmelumatli(melumatli instance);
    partial void Updatemelumatli(melumatli instance);
    partial void Deletemelumatli(melumatli instance);
    partial void Insertteam(team instance);
    partial void Updateteam(team instance);
    partial void Deleteteam(team instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["nurlans1_edufilestockConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<contact> contact
		{
			get
			{
				return this.GetTable<contact>();
			}
		}
		
		public System.Data.Linq.Table<detail> detail
		{
			get
			{
				return this.GetTable<detail>();
			}
		}
		
		public System.Data.Linq.Table<Istifadeci> Istifadeci
		{
			get
			{
				return this.GetTable<Istifadeci>();
			}
		}
		
		public System.Data.Linq.Table<istip> istip
		{
			get
			{
				return this.GetTable<istip>();
			}
		}
		
		public System.Data.Linq.Table<melumataltli> melumataltli
		{
			get
			{
				return this.GetTable<melumataltli>();
			}
		}
		
		public System.Data.Linq.Table<melumatli> melumatli
		{
			get
			{
				return this.GetTable<melumatli>();
			}
		}
		
		public System.Data.Linq.Table<team> team
		{
			get
			{
				return this.GetTable<team>();
			}
		}
		
		public System.Data.Linq.Table<detalmain> detalmain
		{
			get
			{
				return this.GetTable<detalmain>();
			}
		}
		
		public System.Data.Linq.Table<limain> limain
		{
			get
			{
				return this.GetTable<limain>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.contact")]
	public partial class contact : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ContactId;
		
		private string _ContactName;
		
		private string _ContactMail;
		
		private string _ContactText;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnContactIdChanging(int value);
    partial void OnContactIdChanged();
    partial void OnContactNameChanging(string value);
    partial void OnContactNameChanged();
    partial void OnContactMailChanging(string value);
    partial void OnContactMailChanged();
    partial void OnContactTextChanging(string value);
    partial void OnContactTextChanged();
    #endregion
		
		public contact()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ContactId
		{
			get
			{
				return this._ContactId;
			}
			set
			{
				if ((this._ContactId != value))
				{
					this.OnContactIdChanging(value);
					this.SendPropertyChanging();
					this._ContactId = value;
					this.SendPropertyChanged("ContactId");
					this.OnContactIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactName", DbType="NVarChar(MAX)")]
		public string ContactName
		{
			get
			{
				return this._ContactName;
			}
			set
			{
				if ((this._ContactName != value))
				{
					this.OnContactNameChanging(value);
					this.SendPropertyChanging();
					this._ContactName = value;
					this.SendPropertyChanged("ContactName");
					this.OnContactNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactMail", DbType="NVarChar(MAX)")]
		public string ContactMail
		{
			get
			{
				return this._ContactMail;
			}
			set
			{
				if ((this._ContactMail != value))
				{
					this.OnContactMailChanging(value);
					this.SendPropertyChanging();
					this._ContactMail = value;
					this.SendPropertyChanged("ContactMail");
					this.OnContactMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContactText", DbType="NVarChar(MAX)")]
		public string ContactText
		{
			get
			{
				return this._ContactText;
			}
			set
			{
				if ((this._ContactText != value))
				{
					this.OnContactTextChanging(value);
					this.SendPropertyChanging();
					this._ContactText = value;
					this.SendPropertyChanged("ContactText");
					this.OnContactTextChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.detail")]
	public partial class detail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DetailId;
		
		private System.Nullable<int> _DetailLiId;
		
		private string _DetailAd;
		
		private System.DateTime _DetailTarix;
		
		private string _DetailPaylaşan;
		
		private string _DetailIlkP;
		
		private string _DetailOrtaP;
		
		private string _DetailPhoto1;
		
		private string _DetailPhoto2;
		
		private string _DetailPhoto3;
		
		private string _DetailFile;
		
		private string _DetailVideoLink;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDetailIdChanging(int value);
    partial void OnDetailIdChanged();
    partial void OnDetailLiIdChanging(System.Nullable<int> value);
    partial void OnDetailLiIdChanged();
    partial void OnDetailAdChanging(string value);
    partial void OnDetailAdChanged();
    partial void OnDetailTarixChanging(System.DateTime value);
    partial void OnDetailTarixChanged();
    partial void OnDetailPaylaşanChanging(string value);
    partial void OnDetailPaylaşanChanged();
    partial void OnDetailIlkPChanging(string value);
    partial void OnDetailIlkPChanged();
    partial void OnDetailOrtaPChanging(string value);
    partial void OnDetailOrtaPChanged();
    partial void OnDetailPhoto1Changing(string value);
    partial void OnDetailPhoto1Changed();
    partial void OnDetailPhoto2Changing(string value);
    partial void OnDetailPhoto2Changed();
    partial void OnDetailPhoto3Changing(string value);
    partial void OnDetailPhoto3Changed();
    partial void OnDetailFileChanging(string value);
    partial void OnDetailFileChanged();
    partial void OnDetailVideoLinkChanging(string value);
    partial void OnDetailVideoLinkChanged();
    #endregion
		
		public detail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DetailId
		{
			get
			{
				return this._DetailId;
			}
			set
			{
				if ((this._DetailId != value))
				{
					this.OnDetailIdChanging(value);
					this.SendPropertyChanging();
					this._DetailId = value;
					this.SendPropertyChanged("DetailId");
					this.OnDetailIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailLiId", DbType="Int")]
		public System.Nullable<int> DetailLiId
		{
			get
			{
				return this._DetailLiId;
			}
			set
			{
				if ((this._DetailLiId != value))
				{
					this.OnDetailLiIdChanging(value);
					this.SendPropertyChanging();
					this._DetailLiId = value;
					this.SendPropertyChanged("DetailLiId");
					this.OnDetailLiIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailAd", DbType="NVarChar(MAX)")]
		public string DetailAd
		{
			get
			{
				return this._DetailAd;
			}
			set
			{
				if ((this._DetailAd != value))
				{
					this.OnDetailAdChanging(value);
					this.SendPropertyChanging();
					this._DetailAd = value;
					this.SendPropertyChanged("DetailAd");
					this.OnDetailAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailTarix", DbType="Date NOT NULL")]
		public System.DateTime DetailTarix
		{
			get
			{
				return this._DetailTarix;
			}
			set
			{
				if ((this._DetailTarix != value))
				{
					this.OnDetailTarixChanging(value);
					this.SendPropertyChanging();
					this._DetailTarix = value;
					this.SendPropertyChanged("DetailTarix");
					this.OnDetailTarixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailPaylaşan", DbType="NVarChar(MAX)")]
		public string DetailPaylaşan
		{
			get
			{
				return this._DetailPaylaşan;
			}
			set
			{
				if ((this._DetailPaylaşan != value))
				{
					this.OnDetailPaylaşanChanging(value);
					this.SendPropertyChanging();
					this._DetailPaylaşan = value;
					this.SendPropertyChanged("DetailPaylaşan");
					this.OnDetailPaylaşanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailIlkP", DbType="NVarChar(MAX)")]
		public string DetailIlkP
		{
			get
			{
				return this._DetailIlkP;
			}
			set
			{
				if ((this._DetailIlkP != value))
				{
					this.OnDetailIlkPChanging(value);
					this.SendPropertyChanging();
					this._DetailIlkP = value;
					this.SendPropertyChanged("DetailIlkP");
					this.OnDetailIlkPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailOrtaP", DbType="NVarChar(MAX)")]
		public string DetailOrtaP
		{
			get
			{
				return this._DetailOrtaP;
			}
			set
			{
				if ((this._DetailOrtaP != value))
				{
					this.OnDetailOrtaPChanging(value);
					this.SendPropertyChanging();
					this._DetailOrtaP = value;
					this.SendPropertyChanged("DetailOrtaP");
					this.OnDetailOrtaPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailPhoto1", DbType="NVarChar(MAX)")]
		public string DetailPhoto1
		{
			get
			{
				return this._DetailPhoto1;
			}
			set
			{
				if ((this._DetailPhoto1 != value))
				{
					this.OnDetailPhoto1Changing(value);
					this.SendPropertyChanging();
					this._DetailPhoto1 = value;
					this.SendPropertyChanged("DetailPhoto1");
					this.OnDetailPhoto1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailPhoto2", DbType="NVarChar(MAX)")]
		public string DetailPhoto2
		{
			get
			{
				return this._DetailPhoto2;
			}
			set
			{
				if ((this._DetailPhoto2 != value))
				{
					this.OnDetailPhoto2Changing(value);
					this.SendPropertyChanging();
					this._DetailPhoto2 = value;
					this.SendPropertyChanged("DetailPhoto2");
					this.OnDetailPhoto2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailPhoto3", DbType="NVarChar(MAX)")]
		public string DetailPhoto3
		{
			get
			{
				return this._DetailPhoto3;
			}
			set
			{
				if ((this._DetailPhoto3 != value))
				{
					this.OnDetailPhoto3Changing(value);
					this.SendPropertyChanging();
					this._DetailPhoto3 = value;
					this.SendPropertyChanged("DetailPhoto3");
					this.OnDetailPhoto3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailFile", DbType="NVarChar(MAX)")]
		public string DetailFile
		{
			get
			{
				return this._DetailFile;
			}
			set
			{
				if ((this._DetailFile != value))
				{
					this.OnDetailFileChanging(value);
					this.SendPropertyChanging();
					this._DetailFile = value;
					this.SendPropertyChanged("DetailFile");
					this.OnDetailFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailVideoLink", DbType="NVarChar(MAX)")]
		public string DetailVideoLink
		{
			get
			{
				return this._DetailVideoLink;
			}
			set
			{
				if ((this._DetailVideoLink != value))
				{
					this.OnDetailVideoLinkChanging(value);
					this.SendPropertyChanging();
					this._DetailVideoLink = value;
					this.SendPropertyChanged("DetailVideoLink");
					this.OnDetailVideoLinkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Istifadeci")]
	public partial class Istifadeci : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IstifadeciId;
		
		private string _IstifadeciTamAd;
		
		private string _IstifadeciTelefon;
		
		private string _IstifadeciPhoto;
		
		private System.Nullable<int> _IstifadeciTipId;
		
		private string _IstifadeciMail;
		
		private System.Nullable<int> _IstifadeciQurtar;
		
		private string _IstifadeciParol;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIstifadeciIdChanging(int value);
    partial void OnIstifadeciIdChanged();
    partial void OnIstifadeciTamAdChanging(string value);
    partial void OnIstifadeciTamAdChanged();
    partial void OnIstifadeciTelefonChanging(string value);
    partial void OnIstifadeciTelefonChanged();
    partial void OnIstifadeciPhotoChanging(string value);
    partial void OnIstifadeciPhotoChanged();
    partial void OnIstifadeciTipIdChanging(System.Nullable<int> value);
    partial void OnIstifadeciTipIdChanged();
    partial void OnIstifadeciMailChanging(string value);
    partial void OnIstifadeciMailChanged();
    partial void OnIstifadeciQurtarChanging(System.Nullable<int> value);
    partial void OnIstifadeciQurtarChanged();
    partial void OnIstifadeciParolChanging(string value);
    partial void OnIstifadeciParolChanged();
    #endregion
		
		public Istifadeci()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IstifadeciId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IstifadeciId
		{
			get
			{
				return this._IstifadeciId;
			}
			set
			{
				if ((this._IstifadeciId != value))
				{
					this.OnIstifadeciIdChanging(value);
					this.SendPropertyChanging();
					this._IstifadeciId = value;
					this.SendPropertyChanged("IstifadeciId");
					this.OnIstifadeciIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IstifadeciTamAd", DbType="NVarChar(MAX)")]
		public string IstifadeciTamAd
		{
			get
			{
				return this._IstifadeciTamAd;
			}
			set
			{
				if ((this._IstifadeciTamAd != value))
				{
					this.OnIstifadeciTamAdChanging(value);
					this.SendPropertyChanging();
					this._IstifadeciTamAd = value;
					this.SendPropertyChanged("IstifadeciTamAd");
					this.OnIstifadeciTamAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IstifadeciTelefon", DbType="NVarChar(MAX)")]
		public string IstifadeciTelefon
		{
			get
			{
				return this._IstifadeciTelefon;
			}
			set
			{
				if ((this._IstifadeciTelefon != value))
				{
					this.OnIstifadeciTelefonChanging(value);
					this.SendPropertyChanging();
					this._IstifadeciTelefon = value;
					this.SendPropertyChanged("IstifadeciTelefon");
					this.OnIstifadeciTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IstifadeciPhoto", DbType="NVarChar(MAX)")]
		public string IstifadeciPhoto
		{
			get
			{
				return this._IstifadeciPhoto;
			}
			set
			{
				if ((this._IstifadeciPhoto != value))
				{
					this.OnIstifadeciPhotoChanging(value);
					this.SendPropertyChanging();
					this._IstifadeciPhoto = value;
					this.SendPropertyChanged("IstifadeciPhoto");
					this.OnIstifadeciPhotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IstifadeciTipId", DbType="Int")]
		public System.Nullable<int> IstifadeciTipId
		{
			get
			{
				return this._IstifadeciTipId;
			}
			set
			{
				if ((this._IstifadeciTipId != value))
				{
					this.OnIstifadeciTipIdChanging(value);
					this.SendPropertyChanging();
					this._IstifadeciTipId = value;
					this.SendPropertyChanged("IstifadeciTipId");
					this.OnIstifadeciTipIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IstifadeciMail", DbType="NVarChar(MAX)")]
		public string IstifadeciMail
		{
			get
			{
				return this._IstifadeciMail;
			}
			set
			{
				if ((this._IstifadeciMail != value))
				{
					this.OnIstifadeciMailChanging(value);
					this.SendPropertyChanging();
					this._IstifadeciMail = value;
					this.SendPropertyChanged("IstifadeciMail");
					this.OnIstifadeciMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IstifadeciQurtar", DbType="Int")]
		public System.Nullable<int> IstifadeciQurtar
		{
			get
			{
				return this._IstifadeciQurtar;
			}
			set
			{
				if ((this._IstifadeciQurtar != value))
				{
					this.OnIstifadeciQurtarChanging(value);
					this.SendPropertyChanging();
					this._IstifadeciQurtar = value;
					this.SendPropertyChanged("IstifadeciQurtar");
					this.OnIstifadeciQurtarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IstifadeciParol", DbType="NVarChar(MAX)")]
		public string IstifadeciParol
		{
			get
			{
				return this._IstifadeciParol;
			}
			set
			{
				if ((this._IstifadeciParol != value))
				{
					this.OnIstifadeciParolChanging(value);
					this.SendPropertyChanging();
					this._IstifadeciParol = value;
					this.SendPropertyChanged("IstifadeciParol");
					this.OnIstifadeciParolChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.istip")]
	public partial class istip : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TipId;
		
		private string _TipAd;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTipIdChanging(int value);
    partial void OnTipIdChanged();
    partial void OnTipAdChanging(string value);
    partial void OnTipAdChanged();
    #endregion
		
		public istip()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TipId
		{
			get
			{
				return this._TipId;
			}
			set
			{
				if ((this._TipId != value))
				{
					this.OnTipIdChanging(value);
					this.SendPropertyChanging();
					this._TipId = value;
					this.SendPropertyChanged("TipId");
					this.OnTipIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipAd", DbType="NVarChar(MAX)")]
		public string TipAd
		{
			get
			{
				return this._TipAd;
			}
			set
			{
				if ((this._TipAd != value))
				{
					this.OnTipAdChanging(value);
					this.SendPropertyChanging();
					this._TipAd = value;
					this.SendPropertyChanged("TipAd");
					this.OnTipAdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.melumataltli")]
	public partial class melumataltli : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MelumatAltLiId;
		
		private string _MelumatAltLiAd;
		
		private System.Nullable<int> _MelumatAltLiMelumatId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMelumatAltLiIdChanging(int value);
    partial void OnMelumatAltLiIdChanged();
    partial void OnMelumatAltLiAdChanging(string value);
    partial void OnMelumatAltLiAdChanged();
    partial void OnMelumatAltLiMelumatIdChanging(System.Nullable<int> value);
    partial void OnMelumatAltLiMelumatIdChanged();
    #endregion
		
		public melumataltli()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MelumatAltLiId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MelumatAltLiId
		{
			get
			{
				return this._MelumatAltLiId;
			}
			set
			{
				if ((this._MelumatAltLiId != value))
				{
					this.OnMelumatAltLiIdChanging(value);
					this.SendPropertyChanging();
					this._MelumatAltLiId = value;
					this.SendPropertyChanged("MelumatAltLiId");
					this.OnMelumatAltLiIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MelumatAltLiAd", DbType="NVarChar(MAX)")]
		public string MelumatAltLiAd
		{
			get
			{
				return this._MelumatAltLiAd;
			}
			set
			{
				if ((this._MelumatAltLiAd != value))
				{
					this.OnMelumatAltLiAdChanging(value);
					this.SendPropertyChanging();
					this._MelumatAltLiAd = value;
					this.SendPropertyChanged("MelumatAltLiAd");
					this.OnMelumatAltLiAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MelumatAltLiMelumatId", DbType="Int")]
		public System.Nullable<int> MelumatAltLiMelumatId
		{
			get
			{
				return this._MelumatAltLiMelumatId;
			}
			set
			{
				if ((this._MelumatAltLiMelumatId != value))
				{
					this.OnMelumatAltLiMelumatIdChanging(value);
					this.SendPropertyChanging();
					this._MelumatAltLiMelumatId = value;
					this.SendPropertyChanged("MelumatAltLiMelumatId");
					this.OnMelumatAltLiMelumatIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.melumatli")]
	public partial class melumatli : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MelumatId;
		
		private string _MelumatAd;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMelumatIdChanging(int value);
    partial void OnMelumatIdChanged();
    partial void OnMelumatAdChanging(string value);
    partial void OnMelumatAdChanged();
    #endregion
		
		public melumatli()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MelumatId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MelumatId
		{
			get
			{
				return this._MelumatId;
			}
			set
			{
				if ((this._MelumatId != value))
				{
					this.OnMelumatIdChanging(value);
					this.SendPropertyChanging();
					this._MelumatId = value;
					this.SendPropertyChanged("MelumatId");
					this.OnMelumatIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MelumatAd", DbType="NVarChar(MAX)")]
		public string MelumatAd
		{
			get
			{
				return this._MelumatAd;
			}
			set
			{
				if ((this._MelumatAd != value))
				{
					this.OnMelumatAdChanging(value);
					this.SendPropertyChanging();
					this._MelumatAd = value;
					this.SendPropertyChanged("MelumatAd");
					this.OnMelumatAdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.team")]
	public partial class team : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TeamId;
		
		private string _TeamName;
		
		private string _TeamJob;
		
		private string _TeamText;
		
		private string _TeamFb;
		
		private string _TeamInst;
		
		private string _TeamTvit;
		
		private string _TeamVik;
		
		private string _TeamPhoto;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTeamIdChanging(int value);
    partial void OnTeamIdChanged();
    partial void OnTeamNameChanging(string value);
    partial void OnTeamNameChanged();
    partial void OnTeamJobChanging(string value);
    partial void OnTeamJobChanged();
    partial void OnTeamTextChanging(string value);
    partial void OnTeamTextChanged();
    partial void OnTeamFbChanging(string value);
    partial void OnTeamFbChanged();
    partial void OnTeamInstChanging(string value);
    partial void OnTeamInstChanged();
    partial void OnTeamTvitChanging(string value);
    partial void OnTeamTvitChanged();
    partial void OnTeamVikChanging(string value);
    partial void OnTeamVikChanged();
    partial void OnTeamPhotoChanging(string value);
    partial void OnTeamPhotoChanged();
    #endregion
		
		public team()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TeamId
		{
			get
			{
				return this._TeamId;
			}
			set
			{
				if ((this._TeamId != value))
				{
					this.OnTeamIdChanging(value);
					this.SendPropertyChanging();
					this._TeamId = value;
					this.SendPropertyChanged("TeamId");
					this.OnTeamIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamName", DbType="NVarChar(MAX)")]
		public string TeamName
		{
			get
			{
				return this._TeamName;
			}
			set
			{
				if ((this._TeamName != value))
				{
					this.OnTeamNameChanging(value);
					this.SendPropertyChanging();
					this._TeamName = value;
					this.SendPropertyChanged("TeamName");
					this.OnTeamNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamJob", DbType="NVarChar(MAX)")]
		public string TeamJob
		{
			get
			{
				return this._TeamJob;
			}
			set
			{
				if ((this._TeamJob != value))
				{
					this.OnTeamJobChanging(value);
					this.SendPropertyChanging();
					this._TeamJob = value;
					this.SendPropertyChanged("TeamJob");
					this.OnTeamJobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamText", DbType="NVarChar(MAX)")]
		public string TeamText
		{
			get
			{
				return this._TeamText;
			}
			set
			{
				if ((this._TeamText != value))
				{
					this.OnTeamTextChanging(value);
					this.SendPropertyChanging();
					this._TeamText = value;
					this.SendPropertyChanged("TeamText");
					this.OnTeamTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamFb", DbType="NVarChar(MAX)")]
		public string TeamFb
		{
			get
			{
				return this._TeamFb;
			}
			set
			{
				if ((this._TeamFb != value))
				{
					this.OnTeamFbChanging(value);
					this.SendPropertyChanging();
					this._TeamFb = value;
					this.SendPropertyChanged("TeamFb");
					this.OnTeamFbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamInst", DbType="NVarChar(MAX)")]
		public string TeamInst
		{
			get
			{
				return this._TeamInst;
			}
			set
			{
				if ((this._TeamInst != value))
				{
					this.OnTeamInstChanging(value);
					this.SendPropertyChanging();
					this._TeamInst = value;
					this.SendPropertyChanged("TeamInst");
					this.OnTeamInstChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamTvit", DbType="NVarChar(MAX)")]
		public string TeamTvit
		{
			get
			{
				return this._TeamTvit;
			}
			set
			{
				if ((this._TeamTvit != value))
				{
					this.OnTeamTvitChanging(value);
					this.SendPropertyChanging();
					this._TeamTvit = value;
					this.SendPropertyChanged("TeamTvit");
					this.OnTeamTvitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamVik", DbType="NVarChar(MAX)")]
		public string TeamVik
		{
			get
			{
				return this._TeamVik;
			}
			set
			{
				if ((this._TeamVik != value))
				{
					this.OnTeamVikChanging(value);
					this.SendPropertyChanging();
					this._TeamVik = value;
					this.SendPropertyChanged("TeamVik");
					this.OnTeamVikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamPhoto", DbType="NVarChar(MAX)")]
		public string TeamPhoto
		{
			get
			{
				return this._TeamPhoto;
			}
			set
			{
				if ((this._TeamPhoto != value))
				{
					this.OnTeamPhotoChanging(value);
					this.SendPropertyChanging();
					this._TeamPhoto = value;
					this.SendPropertyChanged("TeamPhoto");
					this.OnTeamPhotoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.detalmain")]
	public partial class detalmain
	{
		
		private int _DetailId;
		
		private System.Nullable<int> _DetailLiId;
		
		private string _DetailAd;
		
		private System.DateTime _DetailTarix;
		
		private string _DetailPaylaşan;
		
		private string _DetailIlkP;
		
		private string _DetailOrtaP;
		
		private string _DetailPhoto1;
		
		private string _DetailPhoto2;
		
		private string _DetailPhoto3;
		
		private string _DetailFile;
		
		private string _DetailVideoLink;
		
		private System.Nullable<int> _MelumatAltLiId;
		
		private string _MelumatAltLiAd;
		
		private System.Nullable<int> _MelumatAltLiMelumatId;
		
		public detalmain()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailId", DbType="Int NOT NULL")]
		public int DetailId
		{
			get
			{
				return this._DetailId;
			}
			set
			{
				if ((this._DetailId != value))
				{
					this._DetailId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailLiId", DbType="Int")]
		public System.Nullable<int> DetailLiId
		{
			get
			{
				return this._DetailLiId;
			}
			set
			{
				if ((this._DetailLiId != value))
				{
					this._DetailLiId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailAd", DbType="NVarChar(MAX)")]
		public string DetailAd
		{
			get
			{
				return this._DetailAd;
			}
			set
			{
				if ((this._DetailAd != value))
				{
					this._DetailAd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailTarix", DbType="Date NOT NULL")]
		public System.DateTime DetailTarix
		{
			get
			{
				return this._DetailTarix;
			}
			set
			{
				if ((this._DetailTarix != value))
				{
					this._DetailTarix = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailPaylaşan", DbType="NVarChar(MAX)")]
		public string DetailPaylaşan
		{
			get
			{
				return this._DetailPaylaşan;
			}
			set
			{
				if ((this._DetailPaylaşan != value))
				{
					this._DetailPaylaşan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailIlkP", DbType="NVarChar(MAX)")]
		public string DetailIlkP
		{
			get
			{
				return this._DetailIlkP;
			}
			set
			{
				if ((this._DetailIlkP != value))
				{
					this._DetailIlkP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailOrtaP", DbType="NVarChar(MAX)")]
		public string DetailOrtaP
		{
			get
			{
				return this._DetailOrtaP;
			}
			set
			{
				if ((this._DetailOrtaP != value))
				{
					this._DetailOrtaP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailPhoto1", DbType="NVarChar(MAX)")]
		public string DetailPhoto1
		{
			get
			{
				return this._DetailPhoto1;
			}
			set
			{
				if ((this._DetailPhoto1 != value))
				{
					this._DetailPhoto1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailPhoto2", DbType="NVarChar(MAX)")]
		public string DetailPhoto2
		{
			get
			{
				return this._DetailPhoto2;
			}
			set
			{
				if ((this._DetailPhoto2 != value))
				{
					this._DetailPhoto2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailPhoto3", DbType="NVarChar(MAX)")]
		public string DetailPhoto3
		{
			get
			{
				return this._DetailPhoto3;
			}
			set
			{
				if ((this._DetailPhoto3 != value))
				{
					this._DetailPhoto3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailFile", DbType="NVarChar(MAX)")]
		public string DetailFile
		{
			get
			{
				return this._DetailFile;
			}
			set
			{
				if ((this._DetailFile != value))
				{
					this._DetailFile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DetailVideoLink", DbType="NVarChar(MAX)")]
		public string DetailVideoLink
		{
			get
			{
				return this._DetailVideoLink;
			}
			set
			{
				if ((this._DetailVideoLink != value))
				{
					this._DetailVideoLink = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MelumatAltLiId", DbType="Int")]
		public System.Nullable<int> MelumatAltLiId
		{
			get
			{
				return this._MelumatAltLiId;
			}
			set
			{
				if ((this._MelumatAltLiId != value))
				{
					this._MelumatAltLiId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MelumatAltLiAd", DbType="NVarChar(MAX)")]
		public string MelumatAltLiAd
		{
			get
			{
				return this._MelumatAltLiAd;
			}
			set
			{
				if ((this._MelumatAltLiAd != value))
				{
					this._MelumatAltLiAd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MelumatAltLiMelumatId", DbType="Int")]
		public System.Nullable<int> MelumatAltLiMelumatId
		{
			get
			{
				return this._MelumatAltLiMelumatId;
			}
			set
			{
				if ((this._MelumatAltLiMelumatId != value))
				{
					this._MelumatAltLiMelumatId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.limain")]
	public partial class limain
	{
		
		private int _MelumatAltLiId;
		
		private string _MelumatAltLiAd;
		
		private System.Nullable<int> _MelumatAltLiMelumatId;
		
		private System.Nullable<int> _MelumatId;
		
		private string _MelumatAd;
		
		public limain()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MelumatAltLiId", DbType="Int NOT NULL")]
		public int MelumatAltLiId
		{
			get
			{
				return this._MelumatAltLiId;
			}
			set
			{
				if ((this._MelumatAltLiId != value))
				{
					this._MelumatAltLiId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MelumatAltLiAd", DbType="NVarChar(MAX)")]
		public string MelumatAltLiAd
		{
			get
			{
				return this._MelumatAltLiAd;
			}
			set
			{
				if ((this._MelumatAltLiAd != value))
				{
					this._MelumatAltLiAd = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MelumatAltLiMelumatId", DbType="Int")]
		public System.Nullable<int> MelumatAltLiMelumatId
		{
			get
			{
				return this._MelumatAltLiMelumatId;
			}
			set
			{
				if ((this._MelumatAltLiMelumatId != value))
				{
					this._MelumatAltLiMelumatId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MelumatId", DbType="Int")]
		public System.Nullable<int> MelumatId
		{
			get
			{
				return this._MelumatId;
			}
			set
			{
				if ((this._MelumatId != value))
				{
					this._MelumatId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MelumatAd", DbType="NVarChar(MAX)")]
		public string MelumatAd
		{
			get
			{
				return this._MelumatAd;
			}
			set
			{
				if ((this._MelumatAd != value))
				{
					this._MelumatAd = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
